### ISSUE TITLE
Need to add argparse to requirements.txt

### ISSUE THREAD

**Issue by dolan-a** [mumrah/s3-multipart#1]
argparse missing from requirements.txt; otherwise, looking good so far

**Comment by mumrah** [comment]
Thanks, added. I always forget about the poor souls running old versions of Python

**Comment by mumrah** [comment]
btw, I'm curious what kind of throughput you are able to get with this tool? I've only really tested it from one network

**Comment by dolan-a** [comment]
You using 3.x? argparse standard in it?  For throughput, I got 14Mbps over 500M on 4 threads.  I then got 28Mbps over 5GB on 8 threads.  Those were the only two uploads I've done so far

**Comment by mumrah** [comment]
Those were upload speeds? Nice!

Also, argparse was added to the stdlib in 2.7

Cheers
