### ISSUE TITLE
num_parts calculation bug

### ISSUE THREAD

**Issue by vitaly-krugl** [mumrah/s3-multipart#10]
```
num_parts = int(ceil(size / part_size))
```

size = 4; part_size = 3
In [25]: int(ceil(size / part_size))
Out[25]: 1

I think that the code was hoping to get 2 in this case, but will actually only get 1.

If my understanding of the code's intention is correct, then the following will address it:

```
num_parts = int(ceil(float(size) / part_size))
```

**Comment by mumrah** [comment]
Thanks @vitaly-krugl. This was unintended

**Comment by mumrah** [comment]
The calculation was correct, although it seems odd. Might be that the _right_ thing to do is `int(ceil(1.0 * size / part_size)) - 1`

Unfortunately, I don't have time to maintain this project very much, so I'm just reverting to the known working state.

**Comment by vitaly-krugl** [comment]
This might be the difference between the new division in python 3.x versus the old division in 2.x. The original code would work find on 3.x, but not 2.x.
