### ISSUE TITLE
Commit 78e93309e5 breaks uploading

### ISSUE THREAD

**Issue by accaldwell** [mumrah/s3-multipart#11]
Haven't been able to upload anything with s3-mp-upload since commit 78e93309e5, all uploads fail with:

ERROR:s3-mp-upload:Encountered an error, canceling upload
ERROR:s3-mp-upload:Unexpectedly tried to read an empty chunk

Previous version has no issue.

**Comment by mumrah** [comment]
Thanks, reverting that commit
