### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_key'

### ISSUE THREAD

**Issue by alloylab** [mumrah/s3-multipart#18]
I am running the following command,

python /dir/s3-mp-upload.py -np 25 -f -s 1000 -v /dir/backup/backup.tgz s3://bucket/dir/backup.tgz

and I get the following error,

Traceback (most recent call last):
  File "/dir/s3-mp-upload.py", line 158, in <module>
    main(**arg_dict)
  File "/dir/s3-mp-upload.py", line 86, in main
    key = bucket.get_key(split_rs.path)
AttributeError: 'NoneType' object has no attribute 'get_key'

and for the life of me I can not figure out what I am doing wrong.... I would appreciate any help resolving this issue. Thanks!

**Comment by mumrah** [comment]
@tjferre if `bucket` is None, then either the bucket does not exist or you don't have permission to read it.
