### ISSUE TITLE
What license is s3-multipart under?

### ISSUE THREAD

**Issue by najibninaba** [mumrah/s3-multipart#2]
It's not immediately clear to me what sort of license is s3-multipart? I would like to use it in one of my projects if it is open source.

Best Regards,
-najib

**Comment by mumrah** [comment]
ASLv2 - added a LICENSE file

Glad to hear you're using the utility, hopefully ASL is compatible for you. Let me know what kind of throughput you see with it (particularly upstream).

Cheers,
David
