### ISSUE TITLE
How to choose a split size for s3-mp-upload

### ISSUE THREAD

**Issue by jmound** [mumrah/s3-multipart#4]
Can you point me in the right direction as to how to choose a good split size? I'm putting  >5GB files. The default of 50MB seems low, is there any reason to not increase it?

-Thanks!

**Comment by peppernicus** [comment]
One datapoint:

For us, west coast to S3 standard, there's significant throughput loss above 25MB splits.  That number likely can increase based on your geography, but overall the only benefit to larger splits is reduced calls for the multipart IDs.

I've experienced errors and failed transfers setting it below 10MB, even though 5MB is supposed to be the minimum part size.

**Comment by mumrah** [comment]
Another consideration is how long it takes you to saturate your network. Usually transfers will take a second or two to get to full speed, so if your split size is too small you'll end up spending a lot of time initializing the transfer. You can also set "--np" and it will calculate the split size based on that

**Comment by mumrah** [comment]
What would be nice is if we could resume a failed transfer. Should be possible thanks to the Multipart Upload API

**Comment by mumrah** [comment]
@jmound give larger split size a try. I know I've done hundreds of MB in the past, maybe even GB once

**Comment by jmound** [comment]
I'm having good success with 150 MB for split size.
