### ISSUE TITLE
Why not threads?

### ISSUE THREAD

**Issue by vitaly-krugl** [mumrah/s3-multipart#9]
Hi, I see that s3-multipart is using the multiprocessing module. Why not threads?

**Comment by mumrah** [comment]
Multithreading in Python is somewhat non-existant thanks to the GIL. With multiprocessing you can have actual parallel execution.

**Comment by vitaly-krugl** [comment]
@mumrah: thank you for the follow-up. I was expecting that once in socket send/receive blocks, the GIL would be released by python's C-language code, and normal context switching would prevail.

Vitaly

**Comment by mumrah** [comment]
That is entirely likely. A vast majority of the time, these programs 
will be in the send/recv system calls in which case I believe you are 
correct that the threads would be able to yield. However, this tool 
evolved out of a one-off I did at a previous job and I started using 
multiprocessing from the beginning (probably out of habit). I don't 
think much would be gained or lost from switching to threading, but I'm 
sure not going to do it :)

**Comment by vitaly-krugl** [comment]
Thanks, this was for my own education. I was working on an internal implementation of multi-part upload, and in that app, multi-processing would potentially be prohibitive in terms of physical memory (copy-on-write, etc.).
Best,
Vitaly
